import Head from "next/head";
import Player from "../components/Player";
// import Player from "../app/Player";

import styles from "../styles/Home.module.css";

import { getSortedPostsData, PostData } from "../lib/posts";

export async function getStaticProps() {
  const allPostsData = getSortedPostsData();
  return {
    props: {
      allPostsData,
    },
  };
}

// export default function MyApp({ Component, pageProps }: AppProps) {
export default function Home({
  allPostsData,
}: {
  allPostsData: Array<PostData>;
}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center">
        <div className="flex flex-col h-screen justify-between">
          <header className="h-10 bg-red-500">Header</header>
          <main className="mb-auto h-10 bg-green-500">Content</main>

          <section className={`${styles.headingMd} ${styles.padding1px}`}>
            <h2 className={styles.headingLg}>Blog</h2>
            <ul className={styles.list}>
              {allPostsData.map(({ id, date, title }) => (
                <li className={styles.listItem} key={id}>
                  {title}
                  <br />
                  {id}
                  <br />
                  {date}
                </li>
              ))}
            </ul>
          </section>

          <Player />
        </div>
      </div>
    </>
  );
}
